package io.github.crunchybubbles.geological.petrology;

/** Coarse texture class retained independently from lithology and presentation policy. */
public enum RockTexture {
  APHANITIC_CRYSTALLINE,
  PHANERITIC_CRYSTALLINE,
  ULTRAMAFIC_CRYSTALLINE,
  FOLIATED_CRYSTALLINE,
  SLATY_PHYLLITIC,
  SCHISTOSE,
  NEMATOBLASTIC,
  GRANOBLASTIC,
  CLASTIC_COARSE,
  CLASTIC_SAND,
  CLASTIC_SILT,
  CLASTIC_MUD,
  BEDDED_CARBONATE,
  MICROCRYSTALLINE_SILICA,
  BANDED_IRON_SILICA,
  BEDDED_EVAPORITE,
  ORGANIC_BEDDED,
  VOLCANICLASTIC,
  MASSIVE_SULFIDE,
  UNCONSOLIDATED_GRANULAR
}
