package io.github.crunchybubbles.geological.cli;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertTrue;

import io.github.crunchybubbles.geological.query.Phase2World;
import java.nio.file.Files;
import java.nio.file.Path;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.io.TempDir;

class MaterialReviewPacketGeneratorTest {
  @Test
  void generatedReviewIsDeterministicAndCarriesPhase2ProofState(@TempDir Path temporaryDirectory)
      throws Exception {
    Path first =
        new MaterialReviewPacketGenerator(8_675_309L).generate(temporaryDirectory.resolve("a"));
    Path second =
        new MaterialReviewPacketGenerator(8_675_309L).generate(temporaryDirectory.resolve("b"));

    String firstJson = Files.readString(first);
    assertEquals(firstJson, Files.readString(second));
    assertTrue(firstJson.contains("\"modelVersion\": \"phase2.0-alpha.37\""));
    assertTrue(firstJson.contains(Phase2World.SCIENTIFIC_DIGEST));
    assertTrue(firstJson.contains("\"materialProcess\""));
    assertTrue(firstJson.contains("\"elementReservoirLedgers\""));
    assertTrue(firstJson.contains("\"surfacePlacerContext\""));
    assertTrue(firstJson.contains("\"surfaceColluviumContext\""));
    assertTrue(firstJson.contains("\"surface-colluvial-mantle\""));
    assertTrue(firstJson.contains("\"COLLUVIAL_MANTLE\""));
    assertTrue(firstJson.contains("\"underlyingBedrockBodyId\""));
    assertTrue(firstJson.contains("\"formationAgeMa\": 0.02"));
    assertTrue(firstJson.contains("\"colluvialSourceMix\""));
    assertTrue(firstJson.contains("\"sourceAssemblageFractionPpm\""));
    assertTrue(firstJson.contains("\"weatheredMatrixFractionPpm\""));
    assertTrue(firstJson.contains("\"sedimentYieldPpm\""));
    assertTrue(firstJson.contains("\"textureState\""));
    assertTrue(firstJson.contains("\"grainSizePpm\""));
    assertTrue(firstJson.contains("\"gravelAndCoarser\""));
    assertTrue(firstJson.contains("\"sorting\": \"UNSORTED_TO_POORLY_SORTED\""));
    assertTrue(firstJson.contains("\"clastShape\": \"ANGULAR_TO_SUBROUNDED\""));
    assertTrue(firstJson.contains("\"physicalState\""));
    assertTrue(firstJson.contains("\"porosityQuantile\""));
    assertTrue(firstJson.contains("\"permeabilityQuantile\""));
    assertTrue(firstJson.contains("\"erodibilityQuantile\""));
    assertTrue(firstJson.contains("\"sedimentBudget\""));
    assertTrue(firstJson.contains("\"unit\": \"phase2_normalized_sediment_mass\""));
    assertTrue(
        firstJson.contains(
            "\"grainTransportModel\": \"SLOPE_ROUGHNESS_PATH_CONDITIONED_DRY_RAVEL_PROOF\""));
    assertTrue(firstJson.contains("\"sourceCapacityFixedUnits\": 1000000"));
    assertTrue(firstJson.contains("\"mobilizedInventoryFixedUnits\""));
    assertTrue(firstJson.contains("\"retainedInventoryFixedUnits\""));
    assertTrue(firstJson.contains("\"transportLossFixedUnits\""));
    assertTrue(firstJson.contains("\"bypassedInventoryFixedUnits\""));
    assertTrue(firstJson.contains("\"depositedInventoryFixedUnits\""));
    assertTrue(firstJson.contains("\"capacityGrainMassFixedUnits\""));
    assertTrue(firstJson.contains("\"mobilizedGrainMassFixedUnits\""));
    assertTrue(firstJson.contains("\"retainedGrainMassFixedUnits\""));
    assertTrue(firstJson.contains("\"transportLossGrainMassFixedUnits\""));
    assertTrue(firstJson.contains("\"bypassedGrainMassFixedUnits\""));
    assertTrue(firstJson.contains("\"depositedGrainMassFixedUnits\""));
    assertTrue(firstJson.contains("\"depositedGrainSizePpm\""));
    assertTrue(firstJson.contains("\"sedimentYieldPpm\""));
    assertTrue(firstJson.contains("\"terrainRoughnessIndex\""));
    assertTrue(firstJson.contains("\"terrainPath\""));
    assertTrue(firstJson.contains("\"reachLengthBlocks\": 32"));
    assertTrue(firstJson.contains("\"straightLineDistanceBlocks\""));
    assertTrue(firstJson.contains("\"routedDistanceBlocks\""));
    assertTrue(firstJson.contains("\"routeDirectnessIndex\""));
    assertTrue(firstJson.contains("\"maximumDeflectionFromInitialDegrees\""));
    assertTrue(firstJson.contains("\"reachDecisions\""));
    assertTrue(firstJson.contains("\"rawUpslopeDirection\""));
    assertTrue(firstJson.contains("\"routedUpslopeDirection\""));
    assertTrue(firstJson.contains("\"flatTerrainFallback\""));
    assertTrue(firstJson.contains("\"deflectionClipped\""));
    assertTrue(firstJson.contains("\"routeSamples\""));
    assertTrue(firstJson.contains("\"cumulativeDownslopeReliefBlocks\""));
    assertTrue(firstJson.contains("\"cumulativeBarrierReliefBlocks\""));
    assertTrue(firstJson.contains("\"descendingReachFraction\""));
    assertTrue(firstJson.contains("\"downslopeContinuityIndex\""));
    assertTrue(firstJson.contains("\"transportPathResponse\""));
    assertTrue(firstJson.contains("\"transportDistanceScale\""));
    assertTrue(firstJson.contains("\"transportEFoldingDistanceBlocks\""));
    assertTrue(firstJson.contains("\"weatheredMatrixBalance\""));
    assertTrue(firstJson.contains("\"sourceBalances\""));
    assertTrue(firstJson.contains("\"normalizedDepositFractionPpm\""));
    assertTrue(firstJson.contains("\"sourceContributions\""));
    assertTrue(firstJson.contains("\"initialUpslopeDirection\""));
    assertTrue(firstJson.contains("\"maximumRouteDeflectionDegrees\": 60.0"));
    assertTrue(firstJson.contains("\"sourcePoint\""));
    assertTrue(firstJson.contains("\"sourceProvinceId\""));
    assertTrue(firstJson.contains("\"upslopeDistanceBlocks\": 96"));
    assertTrue(firstJson.contains("\"upslopeDistanceBlocks\": 192"));
    assertTrue(firstJson.contains("\"assemblageFractionPpm\""));
    assertTrue(firstJson.contains("\"capacityFixedUnits\": 350000"));
    assertTrue(firstJson.contains("\"capacityFixedUnits\": 200000"));
    assertTrue(firstJson.contains("\"capacityFixedUnits\": 100000"));
    assertTrue(firstJson.contains("\"normalizedExchangeMagnitudePpm\""));
    assertTrue(firstJson.contains("\"texture\""));
    assertTrue(firstJson.contains("\"responseTexture\""));
    assertTrue(firstJson.contains("\"primaryTexture\""));
    assertTrue(firstJson.contains("\"resolvedTexture\""));
    assertTrue(firstJson.contains("\"HORNFELSIC\""));
    assertTrue(firstJson.contains("\"porosityDistribution\""));
    assertTrue(firstJson.contains("\"modalVariationAxes\""));
    assertTrue(firstJson.contains("\"loadingsPpm\""));
    assertTrue(firstJson.contains("\"solidSolutionCount\""));
    assertTrue(firstJson.contains("\"nonCrystallineConstituentCount\""));
    assertTrue(firstJson.contains("\"constituentCount\""));
    assertTrue(firstJson.contains("geological:solid_solution/plagioclase"));
    assertTrue(firstJson.contains("geological:solid_solution/olivine"));
    assertTrue(firstJson.contains("\"komatiitic-ultramafic-catalog\""));
    assertTrue(firstJson.contains("\"basaltic-catalog\""));
    assertTrue(firstJson.contains("\"gabbroic-catalog\""));
    assertTrue(firstJson.contains("\"andesitic-catalog\""));
    assertTrue(firstJson.contains("\"rhyolitic-catalog\""));
    assertTrue(firstJson.contains("\"PORPHYRITIC_VOLCANIC\""));
    assertTrue(firstJson.contains("\"FELSITIC_FLOW_BANDED\""));
    assertTrue(firstJson.contains("\"alkaline-catalog\""));
    assertTrue(firstJson.contains("\"carbonatitic-catalog\""));
    assertTrue(firstJson.contains("\"FELDSPATHOID_BEARING_CRYSTALLINE\""));
    assertTrue(firstJson.contains("\"MAGMATIC_CARBONATE_CRYSTALLINE\""));
    assertTrue(firstJson.contains("geological:mineral/nepheline"));
    assertTrue(firstJson.contains("geological:mineral/aegirine"));
    assertTrue(firstJson.contains("geological:mineral/fluorapatite"));
    assertTrue(firstJson.contains("\"kimberlitic-catalog\""));
    assertTrue(firstJson.contains("\"MACROCRYSTIC_VOLATILE_RICH\""));
    assertTrue(firstJson.contains("\"pyroclastic-catalog\""));
    assertTrue(firstJson.contains("\"WELDED_FRAGMENTAL\""));
    assertTrue(firstJson.contains("geological:constituent/rhyolitic_volcanic_glass"));
    assertTrue(firstJson.contains("\"GLASS\""));
    assertTrue(firstJson.contains("\"laterite-bauxite-catalog\""));
    assertTrue(firstJson.contains("\"LATERITIC_PISOLITIC\""));
    assertTrue(firstJson.contains("geological:mineral/gibbsite"));
    assertTrue(firstJson.contains("geological:mineral/boehmite"));
    assertTrue(firstJson.contains("\"soil-colluvium-catalog\""));
    assertTrue(firstJson.contains("\"SOIL_COLLUVIAL\""));
    assertTrue(firstJson.contains("\"glacial-till-catalog\""));
    assertTrue(firstJson.contains("\"GLACIAL_DIAMICTIC\""));
    assertTrue(firstJson.contains("\"mantleCargo\""));
    assertTrue(firstJson.contains("\"SOURCE_CONTEXT_UNRESOLVED\""));
    assertTrue(firstJson.contains("\"diamondGradePpbByMass\": 0"));
    assertTrue(firstJson.contains("geological:mineral/diamond"));
    assertTrue(firstJson.contains("geological:mineral/pyrope"));
    assertTrue(firstJson.contains("geological:mineral/chromite"));
    assertTrue(firstJson.contains("geological:mineral/ilmenite"));
    assertTrue(firstJson.contains("geological:mineral/perovskite"));
    assertTrue(firstJson.contains("geological:mineral/dolomite"));
    assertTrue(firstJson.contains("\"siltstone-catalog\""));
    assertTrue(firstJson.contains("\"limestone-catalog\""));
    assertTrue(firstJson.contains("\"dolostone-catalog\""));
    assertTrue(firstJson.contains("\"chert-catalog\""));
    assertTrue(firstJson.contains("\"banded-iron-formation-catalog\""));
    assertTrue(firstJson.contains("geological:mineral/siderite"));
    assertTrue(firstJson.contains("\"gypsum-anhydrite-evaporite-catalog\""));
    assertTrue(firstJson.contains("\"halite-potash-evaporite-catalog\""));
    assertTrue(firstJson.contains("\"coal-catalog\""));
    assertTrue(firstJson.contains("geological:constituent/coal_organic_matter"));
    assertTrue(firstJson.contains("\"ORGANIC_MATTER\""));
    assertTrue(firstJson.contains("\"N\""));
    assertTrue(firstJson.contains("geological:mineral/gypsum"));
    assertTrue(firstJson.contains("geological:mineral/halite"));
    assertTrue(firstJson.contains("\"Cl\""));
    assertTrue(firstJson.contains("\"sedimentaryState\""));
    assertTrue(firstJson.contains("\"dolomitized_carbonate_platform\""));
    assertTrue(firstJson.contains("\"silica_precipitation_and_recrystallization\""));
    assertTrue(firstJson.contains("\"ancient_iron_silica_precipitation_basin\""));
    assertTrue(firstJson.contains("\"chemical_precipitate_redox_controlled\""));
    assertTrue(firstJson.contains("\"buried_peat_mire\""));
    assertTrue(firstJson.contains("\"peat_derived_rank_unresolved\""));
    assertTrue(firstJson.contains("\"slate-phyllite-catalog\""));
    assertTrue(firstJson.contains("\"mica-schist-catalog\""));
    assertTrue(firstJson.contains("\"greenschist-catalog\""));
    assertTrue(firstJson.contains("\"amphibolite-catalog\""));
    assertTrue(firstJson.contains("\"granulite-catalog\""));
    assertTrue(firstJson.contains("\"quartzite-catalog\""));
    assertTrue(firstJson.contains("\"marble-catalog\""));
    assertTrue(firstJson.contains("\"serpentinite-catalog\""));
    assertTrue(firstJson.contains("geological:mineral/lizardite"));
    assertTrue(firstJson.contains("geological:mineral/chrysotile"));
    assertTrue(firstJson.contains("geological:mineral/antigorite"));
    assertTrue(firstJson.contains("geological:mineral/brucite"));
    assertTrue(firstJson.contains("\"SERPENTINIZED_MESH\""));
    assertTrue(firstJson.contains("geological:mineral/magnesiohornblende"));
    assertTrue(firstJson.contains("geological:mineral/ferrohornblende"));
    assertTrue(firstJson.contains("geological:solid_solution/hornblende"));
    assertTrue(firstJson.contains("geological:mineral/graphite"));
    assertTrue(firstJson.contains("geological:mineral/almandine"));
    assertTrue(firstJson.contains("\"primaryMetamorphism\""));
    assertTrue(firstJson.contains("\"protolithRockId\""));
    assertTrue(firstJson.contains("\"grade\""));
    assertTrue(firstJson.contains("\"restricted_evaporite_basin_center\""));
    assertTrue(firstJson.contains("\"salt_recrystallization_dissolution_and_halokinesis\""));
    assertTrue(firstJson.contains("\"magmaLineage\""));
    assertTrue(firstJson.contains("\"endmemberMoleFractionsPpm\""));
    assertTrue(firstJson.contains("\"idealFormulaAtoms\""));
    assertTrue(firstJson.contains("\"protolithFamilies\""));
    assertTrue(firstJson.contains("\"geneticFamily\""));
    assertTrue(firstJson.contains("\"basin-sandstone-phyllic\""));
    assertTrue(firstJson.contains("\"vms-massive-sulfide-gossan\""));
    assertTrue(firstJson.contains("\"ligandCapacities\""));
  }
}
