package io.github.crunchybubbles.geological.cli;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertTrue;

import io.github.crunchybubbles.geological.query.Phase2World;
import java.nio.file.Files;
import java.nio.file.Path;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.io.TempDir;

class MaterialReviewPacketGeneratorTest {
  @Test
  void generatedReviewIsDeterministicAndCarriesPhase2ProofState(@TempDir Path temporaryDirectory)
      throws Exception {
    Path first =
        new MaterialReviewPacketGenerator(8_675_309L).generate(temporaryDirectory.resolve("a"));
    Path second =
        new MaterialReviewPacketGenerator(8_675_309L).generate(temporaryDirectory.resolve("b"));

    String firstJson = Files.readString(first);
    assertEquals(firstJson, Files.readString(second));
    assertTrue(firstJson.contains("\"modelVersion\": \"phase2.0-alpha.94\""));
    assertTrue(firstJson.contains("\"materialBufferState\""));
    assertTrue(firstJson.contains("\"organicCarbonCapacityPpm\""));
    assertTrue(firstJson.contains("\"volatileInventoryPpm\""));
    assertTrue(firstJson.contains("\"fractureTensorState\""));
    assertTrue(firstJson.contains("\"connectivityPpm\""));
    assertTrue(firstJson.contains("\"traceElementVector\""));
    assertTrue(firstJson.contains("\"log10PpmMicros\""));
    assertTrue(firstJson.contains("\"metamorphicPathVocabulary\""));
    assertTrue(firstJson.contains("\"BURIAL_HEATING\""));
    assertTrue(firstJson.contains("\"SUBDUCTION_COLD\""));
    assertTrue(firstJson.contains("\"EXTENSION_DECOMPRESSION\""));
    assertTrue(firstJson.contains("\"POLYMETAMORPHIC\""));
    assertTrue(firstJson.contains("\"strainState\""));
    assertTrue(firstJson.contains("\"shorteningAxisPpm\""));
    assertTrue(firstJson.contains("\"lineationPlungeDegrees\""));
    assertTrue(firstJson.contains("\"strainIntensityPpm\""));
    assertTrue(firstJson.contains("\"residualFluidFractionPpm\""));
    assertTrue(firstJson.contains("\"eventTimeline\""));
    assertTrue(firstJson.contains("\"fluidContributions\""));
    assertTrue(firstJson.contains("\"DECARBONATION\""));
    assertTrue(firstJson.contains("\"CARBON_DIOXIDE\""));
    assertTrue(firstJson.contains("\"PARTIAL_MELTING\""));
    assertTrue(firstJson.contains("\"regionalState\""));
    assertTrue(firstJson.contains("\"reservoirContributions\""));
    assertTrue(firstJson.contains("\"reservoirState\""));
    assertTrue(firstJson.contains("\"aggregateCompositionPpm\""));
    assertTrue(firstJson.contains("\"EVAPORITIC_BRINE\""));
    assertTrue(firstJson.contains("\"transportState\""));
    assertTrue(firstJson.contains("\"waterRockRatioClass\""));
    assertTrue(firstJson.contains("\"phaseBehaviorClass\""));
    assertTrue(firstJson.contains("\"magmaResidualInventoryState\""));
    assertTrue(firstJson.contains("\"residualFluidInventoryPpm\""));
    assertTrue(firstJson.contains("\"magmaThermalState\""));
    assertTrue(firstJson.contains("\"thermalPotentialPpm\""));
    assertTrue(firstJson.contains("\"depthClass\""));
    assertTrue(firstJson.contains("\"porphyrySystemState\""));
    assertTrue(firstJson.contains("\"MAGMATIC_HYDROTHERMAL\""));
    assertTrue(firstJson.contains("\"alterationZones\""));
    assertTrue(firstJson.contains("\"POTASSIC_CORE\""));
    assertTrue(firstJson.contains("\"vmsSystemState\""));
    assertTrue(firstJson.contains("\"STRATIFORM_LENS_WITH_FEEDER\""));
    assertTrue(firstJson.contains("\"seafloorAgeMa\": 241.0"));
    assertTrue(firstJson.contains("\"CHLORITIC_FEEDER\""));
    assertTrue(firstJson.contains("\"lctPegmatiteState\""));
    assertTrue(firstJson.contains("\"LCT_RARE_ELEMENT\""));
    assertTrue(firstJson.contains("\"QUARTZ_CORE\""));
    assertTrue(firstJson.contains("\"bifSystemState\""));
    assertTrue(firstJson.contains("\"ALGOMA_TYPE\""));
    assertTrue(firstJson.contains("\"BANDED_STRATIFORM_SHEET\""));
    assertTrue(firstJson.contains("\"oceanRedoxClass\""));
    assertTrue(firstJson.contains("\"evaporitePotashState\""));
    assertTrue(firstJson.contains("\"REFLOODING_HALITE_TO_POTASH\""));
    assertTrue(firstJson.contains("\"MARGINAL_SULFATE\""));
    assertTrue(firstJson.contains("\"potashAllocationFixedUnits\""));
    assertTrue(firstJson.contains("\"placerSystemState\""));
    assertTrue(firstJson.contains("\"PARTLY_EXPOSED_PRIMARY\""));
    assertTrue(firstJson.contains("\"DENSE_MINERAL_HYDRAULIC_SORTING\""));
    assertTrue(firstJson.contains("\"releasedSourceBudgetFixedUnits\""));
    assertTrue(firstJson.contains("\"retainedSourceBudgetFixedUnits\""));
    assertTrue(firstJson.contains("\"porphyryFluidMetalState\""));
    assertTrue(firstJson.contains("\"VAPOR_RICH_SEPARATED\""));
    assertTrue(firstJson.contains("\"sourceMetalFractionsPpm\""));
    assertTrue(firstJson.contains("\"metalDistributions\""));
    assertTrue(firstJson.contains("\"supergeneCopperState\""));
    assertTrue(firstJson.contains("\"OXIDIZING_VADOSE_PROFILE\""));
    assertTrue(firstJson.contains("\"STABLE_PALEO_WATER_TABLE\""));
    assertTrue(firstJson.contains("\"SUPERGENE_SULFIDE\""));
    assertTrue(firstJson.contains("\"leachableCopperFixedUnits\""));
    assertTrue(firstJson.contains("\"retainedHypogeneFixedUnits\""));
    assertTrue(firstJson.contains("\"mineralSystemValidationReports\""));
    assertTrue(firstJson.contains("\"empiricalDataset\""));
    assertTrue(firstJson.contains("\"SOURCE_ANCHORS_PROVISIONAL\""));
    assertTrue(firstJson.contains("\"calibrationRowCount\": 4"));
    assertTrue(firstJson.contains("\"heldOutRowCount\": 1"));
    assertTrue(firstJson.contains("\"missing_and_censor_flags\""));
    assertTrue(firstJson.contains("\"statisticalValidation\""));
    assertTrue(firstJson.contains("\"quantileComparisons\""));
    assertTrue(firstJson.contains("\"absoluteLog10Error\""));
    assertTrue(firstJson.contains("\"covarianceSummaries\""));
    assertTrue(firstJson.contains("\"INSUFFICIENT_ROWS\""));
    assertTrue(firstJson.contains("\"mineralSystemValidationReports\""));
    assertTrue(firstJson.contains("\"usgs:2026_lct_global\""));
    assertTrue(firstJson.contains("\"usgs:bif_superior_algoma\""));
    assertTrue(firstJson.contains("\"usgs:sir2010_5090s_global_potash\""));
    assertTrue(firstJson.contains("\"diagenesisState\""));
    assertTrue(firstJson.contains("\"phase1Geology\""));
    assertTrue(firstJson.contains("\"phase2Material\""));
    assertTrue(firstJson.contains("\"modelVersion\": \"phase1.0-alpha.2\""));
    assertTrue(firstJson.contains(Phase2World.SCIENTIFIC_DIGEST));
    assertTrue(firstJson.contains("\"materialProcess\""));
    assertTrue(firstJson.contains("\"elementReservoirLedgers\""));
    assertTrue(firstJson.contains("\"surfacePlacerContext\""));
    assertTrue(firstJson.contains("\"surfaceColluviumContext\""));
    assertTrue(firstJson.contains("\"colluvialSourceClaimLedger\""));
    assertTrue(firstJson.contains("\"colluvialSourceCapacityLedger\""));
    assertTrue(firstJson.contains("\"allocatedMobilizedFixedUnits\""));
    assertTrue(firstJson.contains("\"unallocatedMobilizedFixedUnits\""));
    assertTrue(firstJson.contains("\"remainingSourceCapacityFixedUnits\""));
    assertTrue(firstJson.contains("\"claimedCapacityGrainMass\""));
    assertTrue(firstJson.contains("\"allocatedMobilizedGrainMass\""));
    assertTrue(firstJson.contains("\"unallocatedMobilizedGrainMass\""));
    assertTrue(firstJson.contains("\"sourceAggregates\""));
    assertTrue(firstJson.contains("\"surface-colluvial-mantle\""));
    assertTrue(firstJson.contains("\"COLLUVIAL_MANTLE\""));
    assertTrue(firstJson.contains("\"underlyingBedrockBodyId\""));
    assertTrue(firstJson.contains("\"formationAgeMa\": 0.02"));
    assertTrue(firstJson.contains("\"colluvialSourceMix\""));
    assertTrue(firstJson.contains("\"sourceAssemblageFractionPpm\""));
    assertTrue(firstJson.contains("\"weatheredMatrixFractionPpm\""));
    assertTrue(firstJson.contains("\"sedimentYieldPpm\""));
    assertTrue(firstJson.contains("\"textureState\""));
    assertTrue(firstJson.contains("\"grainSizePpm\""));
    assertTrue(firstJson.contains("\"gravelAndCoarser\""));
    assertTrue(firstJson.contains("\"sorting\": \"UNSORTED_TO_POORLY_SORTED\""));
    assertTrue(firstJson.contains("\"clastShape\": \"ANGULAR_TO_SUBROUNDED\""));
    assertTrue(firstJson.contains("\"physicalState\""));
    assertTrue(firstJson.contains("\"porosityQuantile\""));
    assertTrue(firstJson.contains("\"permeabilityQuantile\""));
    assertTrue(firstJson.contains("\"erodibilityQuantile\""));
    assertTrue(firstJson.contains("\"sedimentBudget\""));
    assertTrue(firstJson.contains("\"unit\": \"phase2_normalized_sediment_mass\""));
    assertTrue(
        firstJson.contains(
            "\"grainTransportModel\": \"SLOPE_ROUGHNESS_PATH_GRADE_RUNOFF_CONDITIONED_DRY_RAVEL_PROOF\""));
    assertTrue(firstJson.contains("\"sourceCapacityFixedUnits\": 1000000"));
    assertTrue(firstJson.contains("\"mobilizedInventoryFixedUnits\""));
    assertTrue(firstJson.contains("\"retainedInventoryFixedUnits\""));
    assertTrue(firstJson.contains("\"transportLossFixedUnits\""));
    assertTrue(firstJson.contains("\"bypassedInventoryFixedUnits\""));
    assertTrue(firstJson.contains("\"depositedInventoryFixedUnits\""));
    assertTrue(firstJson.contains("\"capacityGrainMassFixedUnits\""));
    assertTrue(firstJson.contains("\"mobilizedGrainMassFixedUnits\""));
    assertTrue(firstJson.contains("\"retainedGrainMassFixedUnits\""));
    assertTrue(firstJson.contains("\"transportLossGrainMassFixedUnits\""));
    assertTrue(firstJson.contains("\"bypassedGrainMassFixedUnits\""));
    assertTrue(firstJson.contains("\"depositedGrainMassFixedUnits\""));
    assertTrue(firstJson.contains("\"depositedGrainSizePpm\""));
    assertTrue(firstJson.contains("\"sedimentYieldPpm\""));
    assertTrue(firstJson.contains("\"terrainRoughnessIndex\""));
    assertTrue(firstJson.contains("\"runoffIndex\""));
    assertTrue(firstJson.contains("\"transportProcess\""));
    assertTrue(firstJson.contains("\"processClass\""));
    assertTrue(firstJson.contains("\"productionState\""));
    assertTrue(firstJson.contains("\"mobilizationPotential\""));
    assertTrue(firstJson.contains("\"netDepositionFraction\""));
    assertTrue(firstJson.contains("\"sinkState\""));
    assertTrue(firstJson.contains("\"transportLossSink\""));
    assertTrue(firstJson.contains("\"bypassSink\""));
    assertTrue(firstJson.contains("\"sinkAllocation\""));
    assertTrue(firstJson.contains("\"transportLossDistanceBlocks\""));
    assertTrue(firstJson.contains("\"bypassPoint\""));
    assertTrue(firstJson.contains("\"sourceUsages\""));
    assertTrue(firstJson.contains("\"trancheCount\""));
    assertTrue(firstJson.contains("\"sourceGrainShares\""));
    assertTrue(firstJson.contains("\"depositedGrainSizePpm\""));
    assertTrue(firstJson.contains("\"grainSourceShares\""));
    assertTrue(firstJson.contains("\"gravelAndCoarserFractionPpm\""));
    assertTrue(firstJson.contains("\"transportProcessMix\""));
    assertTrue(firstJson.contains("\"dominantProcess\""));
    assertTrue(firstJson.contains("\"hillslopeCreepFractionPpm\""));
    assertTrue(firstJson.contains("\"sheetwashFractionPpm\""));
    assertTrue(firstJson.contains("\"dryRavelFractionPpm\""));
    assertTrue(firstJson.contains("\"transportProcessUsages\""));
    assertTrue(firstJson.contains("\"capacityGrainMassFixedUnits\""));
    assertTrue(firstJson.contains("\"transportProcessStageMix\""));
    assertTrue(firstJson.contains("\"capacity\": {"));
    assertTrue(firstJson.contains("\"arrived\": {"));
    assertTrue(firstJson.contains("\"terrainPath\""));
    assertTrue(firstJson.contains("\"reachLengthBlocks\": 32"));
    assertTrue(firstJson.contains("\"straightLineDistanceBlocks\""));
    assertTrue(firstJson.contains("\"routedDistanceBlocks\""));
    assertTrue(firstJson.contains("\"routeDirectnessIndex\""));
    assertTrue(firstJson.contains("\"routeGradeIndex\""));
    assertTrue(firstJson.contains("\"sortingDominanceIndex\""));
    assertTrue(firstJson.contains("\"horizonState\""));
    assertTrue(firstJson.contains("\"cohesionState\""));
    assertTrue(firstJson.contains("\"cohesionAdjustedErodibilityIndex\""));
    assertTrue(firstJson.contains("\"hydraulicState\""));
    assertTrue(firstJson.contains("\"hydraulicClass\""));
    assertTrue(firstJson.contains("\"runoffPartitionIndex\""));
    assertTrue(firstJson.contains("\"dispersionState\""));
    assertTrue(firstJson.contains("\"weightedSpreadIndex\""));
    assertTrue(firstJson.contains("\"maximumDeflectionFromInitialDegrees\""));
    assertTrue(firstJson.contains("\"reachDecisions\""));
    assertTrue(firstJson.contains("\"rawUpslopeDirection\""));
    assertTrue(firstJson.contains("\"routedUpslopeDirection\""));
    assertTrue(firstJson.contains("\"flatTerrainFallback\""));
    assertTrue(firstJson.contains("\"deflectionClipped\""));
    assertTrue(firstJson.contains("\"routeSamples\""));
    assertTrue(firstJson.contains("\"cumulativeDownslopeReliefBlocks\""));
    assertTrue(firstJson.contains("\"cumulativeBarrierReliefBlocks\""));
    assertTrue(firstJson.contains("\"descendingReachFraction\""));
    assertTrue(firstJson.contains("\"downslopeContinuityIndex\""));
    assertTrue(firstJson.contains("\"transportPathResponse\""));
    assertTrue(firstJson.contains("\"transportDistanceScale\""));
    assertTrue(firstJson.contains("\"transportEFoldingDistanceBlocks\""));
    assertTrue(firstJson.contains("\"weatheredMatrixBalance\""));
    assertTrue(firstJson.contains("\"sourceBalances\""));
    assertTrue(firstJson.contains("\"normalizedDepositFractionPpm\""));
    assertTrue(firstJson.contains("\"sourceContributions\""));
    assertTrue(firstJson.contains("\"initialUpslopeDirection\""));
    assertTrue(firstJson.contains("\"maximumRouteDeflectionDegrees\": 60.0"));
    assertTrue(firstJson.contains("\"routePolicy\""));
    assertTrue(firstJson.contains("\"transportPolicy\""));
    assertTrue(firstJson.contains("\"absoluteMassCalibration\""));
    assertTrue(firstJson.contains("\"caller_supplied_review_proof_scale\""));
    assertTrue(firstJson.contains("\"capacityRate\""));
    assertTrue(firstJson.contains("\"gravelAndCoarserMass\""));
    assertTrue(firstJson.contains("\"finesMass\""));
    assertTrue(firstJson.contains("\"hillslopeCreepResponse\""));
    assertTrue(firstJson.contains("\"sheetwashResponse\""));
    assertTrue(firstJson.contains("\"dryRavelResponse\""));
    assertTrue(firstJson.contains("\"processResponse\""));
    assertTrue(firstJson.contains("\"sinkDestinations\""));
    assertTrue(firstJson.contains("\"receivingBedrockBodyId\""));
    assertTrue(firstJson.contains("\"fixedUnits\""));
    assertTrue(firstJson.contains("\"pathReachLengthBlocks\""));
    assertTrue(firstJson.contains("\"farSourceCapacityFixedUnits\""));
    assertTrue(firstJson.contains("\"sourcePoint\""));
    assertTrue(firstJson.contains("\"sourceProvinceId\""));
    assertTrue(firstJson.contains("\"upslopeDistanceBlocks\": 96"));
    assertTrue(firstJson.contains("\"upslopeDistanceBlocks\": 192"));
    assertTrue(firstJson.contains("\"assemblageFractionPpm\""));
    assertTrue(firstJson.contains("\"capacityFixedUnits\": 350000"));
    assertTrue(firstJson.contains("\"capacityFixedUnits\": 200000"));
    assertTrue(firstJson.contains("\"capacityFixedUnits\": 100000"));
    assertTrue(firstJson.contains("\"normalizedExchangeMagnitudePpm\""));
    assertTrue(firstJson.contains("\"texture\""));
    assertTrue(firstJson.contains("\"responseTexture\""));
    assertTrue(firstJson.contains("\"primaryTexture\""));
    assertTrue(firstJson.contains("\"resolvedTexture\""));
    assertTrue(firstJson.contains("\"HORNFELSIC\""));
    assertTrue(firstJson.contains("\"porosityDistribution\""));
    assertTrue(firstJson.contains("\"modalVariationAxes\""));
    assertTrue(firstJson.contains("\"loadingsPpm\""));
    assertTrue(firstJson.contains("\"solidSolutionCount\""));
    assertTrue(firstJson.contains("\"nonCrystallineConstituentCount\""));
    assertTrue(firstJson.contains("\"constituentCount\""));
    assertTrue(firstJson.contains("geological:solid_solution/plagioclase"));
    assertTrue(firstJson.contains("geological:solid_solution/olivine"));
    assertTrue(firstJson.contains("\"komatiitic-ultramafic-catalog\""));
    assertTrue(firstJson.contains("\"basaltic-catalog\""));
    assertTrue(firstJson.contains("\"gabbroic-catalog\""));
    assertTrue(firstJson.contains("\"andesitic-catalog\""));
    assertTrue(firstJson.contains("\"rhyolitic-catalog\""));
    assertTrue(firstJson.contains("\"PORPHYRITIC_VOLCANIC\""));
    assertTrue(firstJson.contains("\"FELSITIC_FLOW_BANDED\""));
    assertTrue(firstJson.contains("\"alkaline-catalog\""));
    assertTrue(firstJson.contains("\"carbonatitic-catalog\""));
    assertTrue(firstJson.contains("\"FELDSPATHOID_BEARING_CRYSTALLINE\""));
    assertTrue(firstJson.contains("\"MAGMATIC_CARBONATE_CRYSTALLINE\""));
    assertTrue(firstJson.contains("geological:mineral/nepheline"));
    assertTrue(firstJson.contains("geological:mineral/aegirine"));
    assertTrue(firstJson.contains("geological:mineral/fluorapatite"));
    assertTrue(firstJson.contains("\"kimberlitic-catalog\""));
    assertTrue(firstJson.contains("\"MACROCRYSTIC_VOLATILE_RICH\""));
    assertTrue(firstJson.contains("\"pyroclastic-catalog\""));
    assertTrue(firstJson.contains("\"WELDED_FRAGMENTAL\""));
    assertTrue(firstJson.contains("geological:constituent/rhyolitic_volcanic_glass"));
    assertTrue(firstJson.contains("\"GLASS\""));
    assertTrue(firstJson.contains("\"laterite-bauxite-catalog\""));
    assertTrue(firstJson.contains("\"LATERITIC_PISOLITIC\""));
    assertTrue(firstJson.contains("geological:mineral/gibbsite"));
    assertTrue(firstJson.contains("geological:mineral/boehmite"));
    assertTrue(firstJson.contains("\"soil-colluvium-catalog\""));
    assertTrue(firstJson.contains("\"SOIL_COLLUVIAL\""));
    assertTrue(firstJson.contains("\"glacial-till-catalog\""));
    assertTrue(firstJson.contains("\"GLACIAL_DIAMICTIC\""));
    assertTrue(firstJson.contains("\"mantleCargo\""));
    assertTrue(firstJson.contains("\"SOURCE_CONTEXT_UNRESOLVED\""));
    assertTrue(firstJson.contains("\"diamondGradePpbByMass\": 0"));
    assertTrue(firstJson.contains("geological:mineral/diamond"));
    assertTrue(firstJson.contains("geological:mineral/pyrope"));
    assertTrue(firstJson.contains("geological:mineral/chromite"));
    assertTrue(firstJson.contains("geological:mineral/ilmenite"));
    assertTrue(firstJson.contains("geological:mineral/perovskite"));
    assertTrue(firstJson.contains("geological:mineral/dolomite"));
    assertTrue(firstJson.contains("\"siltstone-catalog\""));
    assertTrue(firstJson.contains("\"limestone-catalog\""));
    assertTrue(firstJson.contains("\"dolostone-catalog\""));
    assertTrue(firstJson.contains("\"chert-catalog\""));
    assertTrue(firstJson.contains("\"banded-iron-formation-catalog\""));
    assertTrue(firstJson.contains("geological:mineral/siderite"));
    assertTrue(firstJson.contains("\"gypsum-anhydrite-evaporite-catalog\""));
    assertTrue(firstJson.contains("\"halite-potash-evaporite-catalog\""));
    assertTrue(firstJson.contains("\"coal-catalog\""));
    assertTrue(firstJson.contains("geological:constituent/coal_organic_matter"));
    assertTrue(firstJson.contains("\"ORGANIC_MATTER\""));
    assertTrue(firstJson.contains("\"N\""));
    assertTrue(firstJson.contains("geological:mineral/gypsum"));
    assertTrue(firstJson.contains("geological:mineral/halite"));
    assertTrue(firstJson.contains("\"Cl\""));
    assertTrue(firstJson.contains("\"sedimentaryState\""));
    assertTrue(firstJson.contains("\"dolomitized_carbonate_platform\""));
    assertTrue(firstJson.contains("\"silica_precipitation_and_recrystallization\""));
    assertTrue(firstJson.contains("\"ancient_iron_silica_precipitation_basin\""));
    assertTrue(firstJson.contains("\"chemical_precipitate_redox_controlled\""));
    assertTrue(firstJson.contains("\"buried_peat_mire\""));
    assertTrue(firstJson.contains("\"peat_derived_rank_unresolved\""));
    assertTrue(firstJson.contains("\"slate-phyllite-catalog\""));
    assertTrue(firstJson.contains("\"mica-schist-catalog\""));
    assertTrue(firstJson.contains("\"greenschist-catalog\""));
    assertTrue(firstJson.contains("\"amphibolite-catalog\""));
    assertTrue(firstJson.contains("\"granulite-catalog\""));
    assertTrue(firstJson.contains("\"quartzite-catalog\""));
    assertTrue(firstJson.contains("\"marble-catalog\""));
    assertTrue(firstJson.contains("\"serpentinite-catalog\""));
    assertTrue(firstJson.contains("geological:mineral/lizardite"));
    assertTrue(firstJson.contains("geological:mineral/chrysotile"));
    assertTrue(firstJson.contains("geological:mineral/antigorite"));
    assertTrue(firstJson.contains("geological:mineral/brucite"));
    assertTrue(firstJson.contains("\"SERPENTINIZED_MESH\""));
    assertTrue(firstJson.contains("geological:mineral/magnesiohornblende"));
    assertTrue(firstJson.contains("geological:mineral/ferrohornblende"));
    assertTrue(firstJson.contains("geological:solid_solution/hornblende"));
    assertTrue(firstJson.contains("geological:mineral/graphite"));
    assertTrue(firstJson.contains("geological:mineral/almandine"));
    assertTrue(firstJson.contains("\"primaryMetamorphism\""));
    assertTrue(firstJson.contains("\"protolithRockId\""));
    assertTrue(firstJson.contains("\"grade\""));
    assertTrue(firstJson.contains("\"restricted_evaporite_basin_center\""));
    assertTrue(firstJson.contains("\"basinState\""));
    assertTrue(firstJson.contains("\"waterBodyConnectivity\""));
    assertTrue(firstJson.contains("\"carbonateProductivityPpm\""));
    assertTrue(firstJson.contains("\"differentiationState\""));
    assertTrue(firstJson.contains("\"cumulativeCrystalFractionPpm\""));
    assertTrue(firstJson.contains("\"residualFluidPotential\""));
    assertTrue(firstJson.contains("\"fertilityTags\""));
    assertTrue(firstJson.contains("\"sourceReservoirIds\""));
    assertTrue(firstJson.contains("\"processState\""));
    assertTrue(firstJson.contains("\"reactionProgressPpm\""));
    assertTrue(firstJson.contains("\"retrogressionPotentialPpm\""));
    assertTrue(firstJson.contains("\"reactionState\""));
    assertTrue(firstJson.contains("\"serpentinizationBalance\""));
    assertTrue(firstJson.contains("\"eventAges\""));
    assertTrue(firstJson.contains("\"alterationContribution\""));
    assertTrue(firstJson.contains("\"mineralModeDeltaPpm\""));
    assertTrue(firstJson.contains("\"confidencePpm\""));
    assertTrue(firstJson.contains("\"ageMa\""));
    assertTrue(firstJson.contains("\"salt_recrystallization_dissolution_and_halokinesis\""));
    assertTrue(firstJson.contains("\"magmaLineage\""));
    assertTrue(firstJson.contains("\"endmemberMoleFractionsPpm\""));
    assertTrue(firstJson.contains("\"idealFormulaAtoms\""));
    assertTrue(firstJson.contains("\"protolithFamilies\""));
    assertTrue(firstJson.contains("\"geneticFamily\""));
    assertTrue(firstJson.contains("\"basin-sandstone-phyllic\""));
    assertTrue(firstJson.contains("\"vms-massive-sulfide-gossan\""));
    assertTrue(firstJson.contains("\"ligandCapacities\""));
  }
}
