package io.github.crunchybubbles.geological.model;

public enum EventType {
  ESTABLISH_BASEMENT,
  RIFT,
  ERODE_UNCONFORMITY,
  OPEN_BASIN,
  DEPOSIT_SEQUENCE,
  VOLCANIC_HYDROTHERMAL_PULSE,
  ARC_EPISODE,
  INTRUDE_MAGMA,
  CONTACT_METAMORPHISM,
  MINERALIZE,
  FOLD,
  FAULT_REACTIVATION,
  UPLIFT_EXHUME,
  WEATHER,
  ERODE_TRANSPORT,
  ERODE_TRANSPORT_DEPOSIT
}
