package io.github.crunchybubbles.geological.model;

public enum Overprint {
  NONE,
  WEATHERED_UNCONFORMITY,
  CONTACT_HORNFELS,
  POTASSIC_ALTERATION,
  PHYLLIC_ALTERATION,
  PROPYLITIC_ALTERATION,
  CHLORITIC_FOOTWALL,
  OXIDIZED_GOSSAN,
  WEATHERED_REGOLITH
}
